current_year:
  # event-id as found in the URI
  event: 39434
  # starting time for visualization (crops off everything before)
  starttime: "2021-11-13T12:00:00"
  # ending time for visualization (crops off everything after)
  endtime: "2021-11-14T22:00:00"
past_year:
  event: 36177
  starttime: "2020-11-14T12:00:00"
  endtime: "2020-11-15T22:00:00"
# how many entries per request should be loaded. depending on fetching cycles, network performance, server performance and client performance,
# Limitation is 200
per_page : 200
# maximum pages per cycle. if fetching the entries falls behind, you may get into trouble fetching on time
# recommendation: not more than 300/per_page, rounded up
max_pages_per_cycle: 2
# cache time in seconds, i.e. how fast shall the website get the latest data from the database. setting this to 0 will impact loading time for users and not grant any speed
cachetime: 120
#mysql database
database:
  address: "192.168.1.10"
  database: "crawl"
  username: "crawler"
  password: "secret"
