# Generated by Django 4.0.6 on 2022-07-14 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Event-ID')),
                ('start', models.DateTimeField(verbose_name='begin of the event')),
                ('end', models.DateTimeField(verbose_name='end of the event')),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('donated_amount_in_cents', models.BigIntegerField(verbose_name='Donation in Cents')),
                ('page', models.BigIntegerField()),
                ('donated_at', models.DateTimeField()),
                ('was_zero', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.event')),
            ],
        ),
    ]
