# Generated by Django 3.2.14 on 2022-11-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.CharField(default='Anonym', max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
