# Generated by Django 4.2.6 on 2024-07-10 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0003_alter_donation_donated_amount_in_cents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.BigIntegerField(verbose_name='Gesamt')),
                ('categories', models.JSONField(verbose_name='Kategoriestatistik')),
                ('timeslice', models.JSONField(verbose_name='Zeitstatistik')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.event')),
            ],
        ),
    ]
