# Generated by Django 4.2.6 on 2024-07-10 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0004_eventstatistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstatistic',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analyse.event'),
        ),
    ]
