# Generated by Django 4.2.6 on 2024-07-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0005_alter_eventstatistic_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstatistic',
            name='categories',
            field=models.JSONField(default=None, verbose_name='Kategoriestatistik'),
        ),
        migrations.AlterField(
            model_name='eventstatistic',
            name='timeslice',
            field=models.JSONField(default=None, verbose_name='Zeitstatistik'),
        ),
        migrations.AlterField(
            model_name='eventstatistic',
            name='total',
            field=models.BigIntegerField(default=0, verbose_name='Gesamt'),
        ),
    ]
