# Generated by Django 4.2.6 on 2024-07-10 09:05

import analyse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0006_alter_eventstatistic_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstatistic',
            name='categories',
            field=models.JSONField(default=analyse.models.EventStatistic._default_categories, verbose_name='Kategoriestatistik'),
        ),
        migrations.AlterField(
            model_name='eventstatistic',
            name='timeslice',
            field=models.JSONField(default=analyse.models.EventStatistic._default_timeslice, verbose_name='Zeitstatistik'),
        ),
    ]
